### PR TITLE
Modular dns-01 challenge providers

### PR DESCRIPTION
**Pull request by janeczku**
~~WIP~~ Mature

- [x] Make DNS challenge modular
- [x] Manual provider
- [x] AWS Route53 provider
- [x] CloudFlare provider
- [x] RFC 2136 provider
- [x] Testing

### CODE REVIEW

**Comment by mholt** [comment]
Ummmm you get a gold star :star:

**Comment by janeczku** [comment]
Thanks! :smile:

**Comment by xenolf** [comment]
Great stuff :D

**Comment by mholt** [comment]
You're on a roll! CloudFlare support will be awesome. :+1:

**Comment by janeczku** [comment]
@mholt not long now :santa:

**Comment by xenolf** [comment]
Is this done yet? I see tests but "Testing" isn't checked yet :D

**Comment by janeczku** [comment]
i wanted to add some more tests in order to check that box with good conscience :bowtie:
it will have to wait until i get back from my trip tomorrow

**Comment by xenolf** [comment]
Alright :+1:

**Comment by janeczku** [comment]
@xenolf  @mholt please review/test :smile:

**Comment by xenolf** [comment]
Awesome! I'll have a look tomorrow :)

**Comment by xenolf** [comment]
Thank you for this! :) Let's hope that boulder will fix the DNS challenge soon!

**Comment by mholt** [comment]
I would also like to thank you for this, @janeczku - great work!! Can't wait to show this off (once LE supports dns-01) and have Caddy start doing it. This will solve a lot of problems.

**Pull request merged**
