### PR TITLE
Gandi DNS: use acme.FindZoneByFqdn function

### PR DESCRIPTION
**Pull request by xi2**
Commit 8512fab modified the cloudflare, dnsimple and route53 providers to use the `acme.FindZoneByFqdn` function. This commit makes the corresponding change to the Gandi provider.

Benefits are a small reduction in code size and keeping code style similar to the other providers.

### CODE REVIEW

**Comment by LukeHandle** [comment]
Guilty as charged. Looks good though, much cleaner :+1:

**Comment by xi2** [comment]
Thanks @LukeHandle. I hope so :)

**Comment by xi2** [comment]
Tests failing on Go 1.4 only. I don't think it's something introduced in this PR?

**Comment by xi2** [comment]
The test failure cause would appear to be [this commit](https://github.com/GoogleCloudPlatform/gcloud-golang/commit/f95c875f2894b735501920cce2ab858f2110b23a) in `google.golang.org/cloud/compute/metadata` which is used by `google.golang.org/api/dns/v1` which is used by the `googlecloud` provider. It uses `http.Request.Cancel` which is Go 1.5+. It's being discussed in [this issue](https://github.com/GoogleCloudPlatform/gcloud-golang/issues/230).

**Comment by xenolf** [comment]
> Looks good though, much cleaner

I agree :)

**Pull request merged**
