### PR TITLE
Add support for new Gandi Beta Platform: LiveDNS 

### PR DESCRIPTION
**Pull request by aslafy-z**
API documentation is available here: http://doc.livedns.gandi.net/

### CODE REVIEW

**Comment by aslafy-z** [comment]
could someone review this pr?

**Comment by girtsf** [comment]
+1, this PR worked for me. (I did have to update go as some dependency got unhappy with ubuntu's default 1.6 version of go.)

**Comment by BusyBusinessCat** [comment]
Another point that I've just noticed, the Gandi API url used here is the "beta" one (https://dns.beta.gandi.net/api/v5). Based on what I saw in the API docs (http://doc.livedns.gandi.net/) I think that now we should use this one : https://dns.api.gandi.net/api/v5

**Comment by aslafy-z** [comment]
Sure, gona review this. Should I call the provider `Gandi V5` (gandiv5) or `Gandi LiveDNS` ?

**Comment by BusyBusinessCat** [comment]
gandiv5 looks good to me :)

**Comment by aslafy-z** [comment]
Could someone review ?

**Comment by Jc2k** [comment]
FWIW, this is working for me - I'm using it successfully for some internal domains. It would be good to get this merged!

(Thanks @aslafy-z!)

**Comment by dyu** [comment]
+1 to getting this merged.  What's the holdup?

**Comment by RX14** [comment]
If you modify your DNS records using the new gandi site (which has now been the default for many months) it shows up on the old API as an "external DNS server" and means you can no longer use the old API to update DNS. This means DNS challenges fail, and this PR is neccesary for me to review my DNS.

**Comment by fullgore** [comment]
Is it possible to merge for the gandi new api clients that want to user letsencrypt, could be great !

**Comment by kalou** [comment]
Hi from Gandi,

I rebased this to master and tested against our API - this works A OK for me.

As far as I can tell, you're using the API in an optimal way. You might want to review a few leftover comments in the provider class that refer to the older API behavior (one mention of XML-RPC, and the description of Present creating a new zone)

About the naming question, for clarity and ease of use, anything with "gandi" in the name is really fine. We like LiveDNS in the description as this describes the specific API endpoint pretty well - v5 is more or less the website version.

Thanks for working on this!
Let us know how we can help get this merged

**Comment by fullgore** [comment]
Thanks Pascal for the review, can't wait to use dnsChallenge again with gandi provider.

**Comment by xenolf** [comment]
Thanks everyone for working on this / reviewing it!
I'm sorry it took me so long to get to it 😟

**Comment by kalou** [comment]
Thank you all! all this work is highly appreciated

**Pull request merged**
