### PR TITLE
[acmev2] Isolate v2 from v1

### PR DESCRIPTION
**Pull request by ldez**
what I have done in this PR:
- use a dedicated `acmev2` package: rename package `acme` to `acmev2` in the folder `acmev2`. This is required by the following things:
  - fix a bug with manual DNS provider (before this PR manual challenge use the v1 code) https://github.com/xenolf/lego/blob/6e962fbfb37f9ea4a8201e32acb1b94ffb3b8398/providers/dns/dns_providers.go#L68-L69
  - allow to use v1 and v2 with the CLI
	- restore v1 code
	- creation of a package `cmd` for the v2 code
	- add `force-v1` as CLI argument
- fix DNSsimple due to https://github.com/dnsimple/dnsimple-go/pull/71
- fix Travis configuration due to https://github.com/miekg/dns/pull/683

The main issue to use type alias or others deprecation techniques is the logger singleton:
- in v1: no changes
- in v2: use a dedicated package `log` to isolate the logger.

I am open to any changes in this PR, if something does not fit the design I will change it with pleasure.

### CODE REVIEW

**Comment by xenolf** [comment]
Thank you for the PR!
I will review it as soon as possible.

**Comment by JakeWarner** [comment]
Any idea when this may be merged? @xenolf Hoping to get wildcard functionality available soon. Thanks for your work! :)

**Comment by ldez** [comment]
@mholt could you have a look to this PR?

I see you have done a [commit](https://github.com/xenolf/lego/commit/fad2257e11ae4ff31ed03739386873aa405dec2d) directly on the `acmev2` that is in conflict with this PR.

**Comment by ldez** [comment]
@xenolf @mholt any news?

**Comment by ldez** [comment]
I rebased on the HEAD of acmev2

**Comment by ldez** [comment]
@xenolf @mholt @wyattjoh any news?

**Comment by ldez** [comment]
I rebased on the HEAD of acmev2.

**Comment by ldez** [comment]
Note that the build of acmev2 branch fails https://travis-ci.org/xenolf/lego/builds/384173286

**Comment by ldez** [comment]
Closed in favor of #549

**Pull request closed without merging**
