### PR TITLE
fix compile error

### PR DESCRIPTION
**Pull request by rxwen**

### CODE REVIEW

**Comment by xenolf** [comment]
Hey! 

I guess your dependencies aren't up-to-date. The function signatures are as they should be.

**Comment by rxwen** [comment]
Hi,

Do you mean the code in providers? 
I encountered this error after I perform a clean git clone. What should I update?

**Comment by xenolf** [comment]
Please run `go get -u github.com/codegangsta/cli` and try to build again.

**Comment by rxwen** [comment]
It worked now.
No wonder I can't believe such a explicit error was pushed to server.

**Pull request closed without merging**
