### PR TITLE
DigitalOcean uses FindZoneByFqdn

### PR DESCRIPTION
**Pull request by willseward**
It looks like there's been enough refactoring so that my last PR is unnecessary. Here's a quick fix using the new solution.

I'll go ahead and close the other PR

### CODE REVIEW

**Comment by LukeHandle** [comment]
Before this change, was DO unable to handle verifying multi-level sub domains? I remember looking at it before and thinking it could based on their API?

Eg. Auth zone is example.com, you want to verify this.is.a.subdomain.example.com

Either way, this PR brings it in-line with the recent changes and it makes more sense this way :+1:

**Comment by willseward** [comment]
Yes, DO could not verify CNAMEs. If the user wants to verify a.example.com but the zone was setup as so that a.exmple.com was a CNAME in the zone example.com, the provider would make an API request for a.example.com which returned a 404.

**Comment by janeczku** [comment]
Nit, but this bug affects any type of subdomain record, not just CNAME type records.

**Comment by willseward** [comment]
Agreed. Just citing a trivial example. This should work for all types of subdomain records.

**Comment by xenolf** [comment]
LGTM :+1:

**Comment by willseward** [comment]
Is there any timeline for a release with this change?

**Comment by xenolf** [comment]
@willseward I'd like to get #179 fixed and then I'll issue a point release.

**Comment by LukeHandle** [comment]
Hey @xenolf, have you had a chance to look at #186  which would fix #179?

**Comment by xenolf** [comment]
FYI v0.3.1 has been released.

**Comment by willseward** [comment]
Thanks @xenolf

**Pull request merged**
