### PR TITLE
Add OVH DNS provider

### PR DESCRIPTION
**Pull request by disaster37**
We add OVH DNS Provider.
To do that we use the official GO librairy https://github.com/ovh/go-ovh

To use the new extention, we must add the folowwing environment variable :
* OVH_ENDPOINT the endpoint API you should to call
* OVH_APPLICATION_KEY the application key
* OVH_APPLICATION_SECRET the application key
* OVH_CONSUMER_KEY the consumer key

To key all, you must to go on "https://eu.api.ovh.com/createToken/" and you must add some right:
* POST /domain/zone/*
* DELETE /domain/zone/*

All the API is documented here: https://api.ovh.com/console/#/domain

### CODE REVIEW

**Comment by xenolf** [comment]
Thank you for providing this pull request :)
I will review it within the next 24 hours.

**Comment by xenolf** [comment]
Could you please run the `go fmt` tool on your additions? It seems like some things are all over the place :)

**Comment by disaster37** [comment]
I have lauched go fmt tool on my addon and on the main. I hope is better ;)

**Comment by xenolf** [comment]
Yes, a lot better now. I'm sorry that it took me so long to respond, but the last few days were pretty intense.
Would you be willing to maintain this provider further? In case of errors and stuff.

**Comment by disaster37** [comment]
yes no problem. All my domain is hosted on Ovh. So I will use and maintain this provider ;)

**Pull request merged**
