### PR TITLE
Add DNS Provider for SAKURA Cloud

### PR DESCRIPTION
**Pull request by yamamoto-febc**
Add support for the [SAKURA Cloud](https://cloud.sakura.ad.jp) DNS.
([SAKURA Cloud](https://cloud.sakura.ad.jp) is one of the most famous IaaS in Japan)

### CODE REVIEW

**Comment by masa23** [comment]
Succeeded in Sakura's cloud 👍

**Comment by ldez** [comment]
@yamamoto-febc could you rebase for PR?

**Comment by yamamoto-febc** [comment]
@ldez 
I have just rebased:+1:

**Comment by yamamoto-febc** [comment]
@ledez,
Thank you for your review.
I pushed some changes. Please review again:pray:

**Pull request merged**
