### PR TITLE
Add support for additional AWS authentication sources

### PR DESCRIPTION
**Pull request by willglynn**
AWS client tools commonly support passing credentials via `AWS_ACCESS_KEY_ID` + `AWS_SECRET_ACCESS_KEY`, but supporting only this is insufficient. For example, access key IDs provided by STS require passing in `AWS_SECURITY_TOKEN` as a third value, and EC2 instances are often provided dynamic credentials at runtime via the EC2 metadata service.

This changeset makes `lego` attempt to find credentials in the same way that the `aws` CLI tool attempts to find credentials. The result is even less auth code than before because `goamz` provides all this with `aws.GetAuth()`.

### CODE REVIEW

**Comment by willglynn** [comment]
Note also that this proposed behavior matches the official AWS SDK's [default credential chain](https://github.com/aws/aws-sdk-go/blob/master/aws/defaults/defaults.go#L78-L96), customarily achieved by [omitting the `Credentials` field of `aws.Config`](http://docs.aws.amazon.com/sdk-for-go/api/aws/Config.html#Credentials-field).

**Comment by janeczku** [comment]
LGTM :+1:

**Comment by mholt** [comment]
I like that this PR is a net gain in LOC because of comments, but is actually a net reduction.

**Comment by xenolf** [comment]
Great PR, thank you!

**Pull request merged**
