### PR TITLE
Add DNS Provider for ClouDNS.net

### LINKED ISSUE #717: Add support for ClouDNS
Add support for ClouDNS provider.

* API documentation: https://www.cloudns.net/wiki/article/42/

### PR DESCRIPTION
**Pull request by tzakrajs**
Adds Support for ClouDNS.net Subscribers with API access (see: https://www.cloudns.net/wiki/article/42/)

Notes:
The boilerplate and testing suite code is largely based off of cloudxns provider (`./providers/dns/cloudxns`) since it had an integrated client (ClouDNS has no golang client library). 
Works only with `auth-id` at the moment, but `sub-auth-id` support could be added.
Found that in practice 2 minutes is a good ttl to use with this provider, 1 minute ttl is too short.

Thanks for your time reviewing this pull request!

Closes #717

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:
- [x] add a description to your PR
- [ ] be able to maintain this provider
- [x] have a homogeneous design with the other providers
- [x] add tests ("live" and units)
```shell
make test
```
- [ ] add [documentation](https://github.com/xenolf/lego/blob/master/CONTRIBUTING.md#dns-providers-api-references)
- [ ] add CLI DNS help: https://github.com/xenolf/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/cmd/cmd_dnshelp.go#L19
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf ./lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -s https://acme-staging-v02.api.letsencrypt.org/directory -d *.example.com -d example.com run
```
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```

**Comment by tzakrajs** [comment]
00:37:33█ tzakrajs@Thomass-MBP█ lego█ dist/lego --dns cloudns --domains tzakrajs.com -m 'tzakrajs@linux.com' run
2019/03/01 00:37:34 [INFO] [tzakrajs.com] acme: Obtaining bundled SAN certificate
2019/03/01 00:37:34 [INFO] [tzakrajs.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/XXXX
2019/03/01 00:37:34 [INFO] [tzakrajs.com] acme: Could not find solver for: tls-alpn-01
2019/03/01 00:37:34 [INFO] [tzakrajs.com] acme: Could not find solver for: http-01
2019/03/01 00:37:34 [INFO] [tzakrajs.com] acme: use dns-01 solver
2019/03/01 00:37:34 [INFO] [tzakrajs.com] acme: Preparing to solve DNS-01
2019/03/01 00:37:35 [INFO] [tzakrajs.com] acme: Trying to solve DNS-01
2019/03/01 00:37:35 [INFO] [tzakrajs.com] acme: Checking DNS record propagation using [192.168.0.1:53]
2019/03/01 00:37:35 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2019/03/01 00:37:35 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:37:38 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:37:40 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:37:42 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:37:44 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:37:47 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:37:49 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:37:51 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:37:53 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:37:56 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:37:58 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:38:00 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:38:02 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:38:05 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:38:07 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:38:09 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:38:18 [INFO] [tzakrajs.com] The server validated our request
2019/03/01 00:38:18 [INFO] [tzakrajs.com] acme: Cleaning DNS-01 challenge
2019/03/01 00:38:19 [INFO] [tzakrajs.com] acme: Validations succeeded; requesting certificates
2019/03/01 00:38:20 [INFO] [tzakrajs.com] Server responded with a certificate.

**Comment by tzakrajs** [comment]
$ rm -rf dist/lego
$ make build
rm -rf dist/ builds/ cover.out
Version: f9d3f02e4321b2d99635789c647c4dfa2a99b707
go build -v -ldflags '-X "main.version=f9d3f02e4321b2d99635789c647c4dfa2a99b707"' -o dist/lego ./cmd/lego/
$ dist/lego -m 'tzakrajs@linux.com' --dns cloudns -s https://acme-staging-v02.api.letsencrypt.org/directory -d *.tzakrajs.com -d tzakrajs.com run
2019/03/01 00:43:54 No key found for account tzakrajs@linux.com. Generating a P384 key.
2019/03/01 00:43:54 Saved key to /Users/tzakrajs/go/src/github.com/xenolf/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/tzakrajs@linux.com/keys/tzakrajs@linux.com.key
2019/03/01 00:43:54 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2019/03/01 00:43:56 [INFO] acme: Registering account for tzakrajs@linux.com
!!!! HEADS UP !!!!

		Your account credentials have been saved in your Let's Encrypt
		configuration directory at "/Users/tzakrajs/go/src/github.com/xenolf/lego/.lego/accounts".
		You should make a secure backup	of this folder now. This
		configuration directory will also contain certificates and
		private keys obtained from Let's Encrypt so making regular
		backups of this folder is ideal.2019/03/01 00:43:56 [INFO] [*.tzakrajs.com, tzakrajs.com] acme: Obtaining bundled SAN certificate
2019/03/01 00:43:56 [INFO] [*.tzakrajs.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/Vc5wPEwzdqkt_2dECt0cTbEfDE1axpI26yPggrT8hZc
2019/03/01 00:43:56 [INFO] [tzakrajs.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/TUyKwy6nIKo9bnhMz-1IadiZVsQ6WnNx_g0qj8iFLBM
2019/03/01 00:43:56 [INFO] [*.tzakrajs.com] acme: use dns-01 solver
2019/03/01 00:43:56 [INFO] [tzakrajs.com] acme: Could not find solver for: tls-alpn-01
2019/03/01 00:43:56 [INFO] [tzakrajs.com] acme: Could not find solver for: http-01
2019/03/01 00:43:56 [INFO] [tzakrajs.com] acme: use dns-01 solver
2019/03/01 00:43:56 [INFO] [*.tzakrajs.com] acme: Preparing to solve DNS-01
2019/03/01 00:43:57 [INFO] [tzakrajs.com] acme: Preparing to solve DNS-01
2019/03/01 00:43:58 [INFO] [*.tzakrajs.com] acme: Trying to solve DNS-01
2019/03/01 00:43:58 [INFO] [*.tzakrajs.com] acme: Checking DNS record propagation using [192.168.0.1:53]
2019/03/01 00:43:58 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2019/03/01 00:43:59 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:01 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:03 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:05 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:07 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:09 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:12 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:14 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:16 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:18 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:21 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:23 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:26 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:28 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:30 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:32 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:34 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:36 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:38 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:40 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:43 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:45 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:47 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:49 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:51 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:53 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:55 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:44:58 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:00 [INFO] [tzakrajs.com] acme: Trying to solve DNS-01
2019/03/01 00:45:00 [INFO] [tzakrajs.com] acme: Checking DNS record propagation using [192.168.0.1:53]
2019/03/01 00:45:00 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2019/03/01 00:45:00 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:02 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:04 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:07 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:09 [INFO] [tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:17 [INFO] [tzakrajs.com] The server validated our request
2019/03/01 00:45:17 [INFO] [*.tzakrajs.com] acme: Cleaning DNS-01 challenge
2019/03/01 00:45:18 [INFO] [tzakrajs.com] acme: Cleaning DNS-01 challenge
2019/03/01 00:45:19 Could not obtain certificates:
	acme: Error -> One or more domains had a problem:
[*.tzakrajs.com] time limit exceeded: last error: NS ns32.cloudns.net. did not return the expected TXT record [fqdn: _acme-challenge.tzakrajs.com., value: -HevvLNKuA-UfcJDsxY6XsmjmjigqLtF7oy091wq1Yk]: WQIZJ2o5XIyjnjiPRScgrYhTWVPfL_ylOksUpLWs8IA ,790KNzqSJoiXQCpsl81CT4e1En9UTk4MB2MRlemTO04
$ dist/lego -m 'tzakrajs@linux.com' --dns cloudns -s https://acme-staging-v02.api.letsencrypt.org/directory -d *.tzakrajs.com -d tzakrajs.com run
2019/03/01 00:45:36 [INFO] [*.tzakrajs.com, tzakrajs.com] acme: Obtaining bundled SAN certificate
2019/03/01 00:45:36 [INFO] [*.tzakrajs.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/TUyKwy6nIKo9bnhMz-1IadiZVsQ6WnNx_g0qj8iFLBM
2019/03/01 00:45:36 [INFO] [tzakrajs.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/Vc5wPEwzdqkt_2dECt0cTbEfDE1axpI26yPggrT8hZc
2019/03/01 00:45:36 [INFO] [tzakrajs.com] acme: authorization already valid; skipping challenge
2019/03/01 00:45:36 [INFO] [*.tzakrajs.com] acme: use dns-01 solver
2019/03/01 00:45:36 [INFO] [*.tzakrajs.com] acme: Preparing to solve DNS-01
2019/03/01 00:45:37 [INFO] [*.tzakrajs.com] acme: Trying to solve DNS-01
2019/03/01 00:45:37 [INFO] [*.tzakrajs.com] acme: Checking DNS record propagation using [192.168.0.1:53]
2019/03/01 00:45:37 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2019/03/01 00:45:37 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:39 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:42 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:44 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:46 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:48 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:51 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:53 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:55 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:45:58 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:00 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:02 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:04 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:07 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:09 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:11 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:13 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:16 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:18 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:21 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:23 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:25 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:27 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:30 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:32 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:34 [INFO] [*.tzakrajs.com] acme: Waiting for DNS record propagation.
2019/03/01 00:46:43 [INFO] [*.tzakrajs.com] The server validated our request
2019/03/01 00:46:43 [INFO] [*.tzakrajs.com] acme: Cleaning DNS-01 challenge
2019/03/01 00:46:43 [INFO] [*.tzakrajs.com, tzakrajs.com] acme: Validations succeeded; requesting certificates
2019/03/01 00:46:44 [INFO] [*.tzakrajs.com] Server responded with a certificate.

**Comment by tzakrajs** [comment]
I am willing to maintain this provider since I will be relying on it for the indefinite future. I have added the documentation, the cli help, and am now passing linter.

**Comment by tzakrajs** [comment]
```
$ make build
rm -rf dist/ builds/ cover.out
Version: 1858966fa8b5329f6d5a82512dac950957a20041
go build -v -ldflags '-X "main.version=1858966fa8b5329f6d5a82512dac950957a20041"' -o dist/lego ./cmd/lego/
$ dist/lego -m 'tzakrajs@linux.com' --dns cloudns -s https://acme-staging-v02.api.letsencrypt.org/directory -d *.cloud-fortress.net -d cloud-fortress.net run
2019/03/01 01:19:00 [INFO] [*.cloud-fortress.net, cloud-fortress.net] acme: Obtaining bundled SAN certificate
2019/03/01 01:19:00 [INFO] [*.cloud-fortress.net] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/GXVLgqXl1vCpeS_ZFqOaiSjGWKZ8HcCHnGKlLI8ghzo
2019/03/01 01:19:00 [INFO] [cloud-fortress.net] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/0XOkEaGxdAIvdaMc4-_W4BFFVI6p_jAhhjAl5YN2ESs
2019/03/01 01:19:00 [INFO] [*.cloud-fortress.net] acme: use dns-01 solver
2019/03/01 01:19:00 [INFO] [cloud-fortress.net] acme: Could not find solver for: tls-alpn-01
2019/03/01 01:19:00 [INFO] [cloud-fortress.net] acme: Could not find solver for: http-01
2019/03/01 01:19:00 [INFO] [cloud-fortress.net] acme: use dns-01 solver
2019/03/01 01:19:00 [INFO] [*.cloud-fortress.net] acme: Preparing to solve DNS-01
2019/03/01 01:19:01 [INFO] [cloud-fortress.net] acme: Preparing to solve DNS-01
2019/03/01 01:19:02 [INFO] [*.cloud-fortress.net] acme: Trying to solve DNS-01
2019/03/01 01:19:02 [INFO] [*.cloud-fortress.net] acme: Checking DNS record propagation using [192.168.0.1:53]
2019/03/01 01:19:02 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2019/03/01 01:19:02 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:04 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:06 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:08 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:11 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:13 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:16 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:18 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:20 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:22 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:25 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:27 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:29 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:31 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:33 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:36 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:38 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:40 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:42 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:44 [INFO] [*.cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:19:53 [INFO] [*.cloud-fortress.net] The server validated our request
2019/03/01 01:19:53 [INFO] [cloud-fortress.net] acme: Trying to solve DNS-01
2019/03/01 01:19:53 [INFO] [cloud-fortress.net] acme: Checking DNS record propagation using [192.168.0.1:53]
2019/03/01 01:19:53 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2019/03/01 01:19:53 [INFO] [cloud-fortress.net] acme: Waiting for DNS record propagation.
2019/03/01 01:20:03 [INFO] [cloud-fortress.net] The server validated our request
2019/03/01 01:20:03 [INFO] [*.cloud-fortress.net] acme: Cleaning DNS-01 challenge
2019/03/01 01:20:04 [INFO] [cloud-fortress.net] acme: Cleaning DNS-01 challenge
2019/03/01 01:20:04 [INFO] [*.cloud-fortress.net, cloud-fortress.net] acme: Validations succeeded; requesting certificates
2019/03/01 01:20:07 [INFO] [*.cloud-fortress.net] Server responded with a certificate.
```

**Comment by ldez** [comment]
You can define the best TTL and PropagantionTimeout instead of use the "default" from lego.
https://github.com/xenolf/lego/pull/813/files#diff-77ab6442f0f8eddc521e79753fbb6eefR28

**Pull request merged**
