### PR TITLE
initialize struct so cli doesn't panic when domains aren't set

### PR DESCRIPTION
**Pull request by drewwells**
fixes a panic when no domains are passed

```
-> % lego
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xaa60d]

goroutine 1 [running]:
github.com/codegangsta/cli.(*StringSlice).String(0x0, 0x0, 0x0)
	/Users/drew/src/github.com/codegangsta/cli/flag.go:99 +0x11d
flag.(*FlagSet).Var(0xc820074180, 0x1504698, 0x0, 0x4354a0, 0x7, 0x477520, 0x1a)
	/usr/local/go151/src/flag/flag.go:766 +0x6e
github.com/codegangsta/cli.StringSliceFlag.Apply.func1(0x4354a0, 0x7)
	/Users/drew/src/github.com/codegangsta/cli/flag.go:131 +0x8b
github.com/codegangsta/cli.eachName(0x4354a0, 0xa, 0xc8200517c8)
	/Users/drew/src/github.com/codegangsta/cli/flag.go:52 +0x11f
github.com/codegangsta/cli.StringSliceFlag.Apply(0x4354a0, 0xa, 0x0, 0x477520, 0x1a, 0x0, 0x0, 0xc820074180)
	/Users/drew/src/github.com/codegangsta/cli/flag.go:132 +0x32b
github.com/codegangsta/cli.(*StringSliceFlag).Apply(0xc8200723c0, 0xc820074180)
	<autogenerated>:21 +0xa0
github.com/codegangsta/cli.flagSet(0x42bbc0, 0x4, 0xc8200c4000, 0x9, 0xe, 0x1504660)
	/Users/drew/src/github.com/codegangsta/cli/flag.go:43 +0x11a
github.com/codegangsta/cli.(*App).Run(0xc8200c2000, 0xc820076180, 0x1, 0x1, 0x0, 0x0)
	/Users/drew/src/github.com/codegangsta/cli/app.go:86 +0x267
main.main()
	/Users/drew/src/github.com/xenolf/lego/cli.go:94 +0xba6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go151/src/runtime/asm_amd64.s:1696 +0x1
```

### CODE REVIEW

**Comment by xenolf** [comment]
Hello and thanks for your pull request :)
Are you just calling lego with no parameters?

**Comment by drewwells** [comment]
Yep, I was. So it wasn't possible to see the default help to find out what parameters are required. It's a bug with codegangsta/cli, cli should be checking for nil somewhere internally (imo).

**Comment by xenolf** [comment]
That's strange, as the same thing is working for me. What OS are you on?
I guess it doesn't hurt to put that initialization in, I'm just curious.

**Comment by drewwells** [comment]
`./logo` (no arguments) doesn't panic for you? OS X

**Comment by drewwells** [comment]
Same thing on linux,

```

drew@dumass [05:31:42] [~/src/github.com/xenolf/lego] [master]
-> % go run *.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xaa60d]

goroutine 1 [running]:
github.com/codegangsta/cli.(*StringSlice).String(0x0, 0x0, 0x0)
	/Users/drew/src/github.com/codegangsta/cli/flag.go:99 +0x11d
flag.(*FlagSet).Var(0xc820018240, 0x13a4698, 0x0, 0x4354a0, 0x7, 0x477520, 0x1a)
	/usr/local/go151/src/flag/flag.go:766 +0x6e
github.com/codegangsta/cli.StringSliceFlag.Apply.func1(0x4354a0, 0x7)
	/Users/drew/src/github.com/codegangsta/cli/flag.go:131 +0x8b
github.com/codegangsta/cli.eachName(0x4354a0, 0xa, 0xc8200517c8)
	/Users/drew/src/github.com/codegangsta/cli/flag.go:52 +0x11f
```

**Comment by xenolf** [comment]
I'm afraid it does not.

```
xenolf@wat:~/Projects/go/src/github.com/xenolf/lego|master
->  ./lego
NAME:
   lego - Let's encrypt client to go!

USAGE:
   ./lego [global options] command [command options] [arguments...]
   
VERSION:
   0.0.2
```

**Comment by drewwells** [comment]
good idea, yep it's fixed in latest cli

**Pull request closed without merging**
