### PR TITLE
Add DNS challenge support for namecheap

### PR DESCRIPTION
**Pull request by beevik**
This PR adds DNS challenge support for [namecheap](https://www.namecheap.com/).

If you decide to accept this PR, please feel free to delay merging it until the changes being made in https://github.com/xenolf/lego/pull/144 are complete.

### CODE REVIEW

**Comment by xenolf** [comment]
Thank you for this :)

I hope to be able to land #144 soon(tm) now that I've got a bit more time on my hands.

**Comment by xi2** [comment]
Hi beevik. I had a quick read through of your code and I wasn't 100% sure it handles TLDs containing a period correctly (such as co.uk or or org.uk). What made me wonder is that given the domain `example.co.uk`, the `splitDomain` function would return `"co", "uk", nil` when I'd imagine it should return `"example", "co.uk", nil`. These values are then sent through to `namecheap.domains.dns.getHosts` as `SLD` and `TLD`. Am I missing something?

For an alternative way to get TLD and SLD, you can see how I do it in #133 by chopping bits off the front of the FQDN until I hit something that the provider acknowledges, or I believe you can do it by querying nameservers which is what #142 is about?

**Comment by beevik** [comment]
Ah good catch.  I just added code to fix this bug.  I decided to use a namecheap API to help determine the TLD/SLD.

**Comment by xi2** [comment]
Ah cool. That's a nice way of doing it.

We'll see what @xenolf thinks is the best for #148, and then we can both change our code accordingly for the timeout issue.

**Comment by xenolf** [comment]
Hey @beevik! Could you please rebase this PR onto current master and move your provider into `lego/providers/dns/namecheap`. Thanks!

**Pull request closed without merging**
