### PR TITLE
add CNAME support for creating dns-01 TXT challenge

### PR DESCRIPTION
**Pull request by gurvindersingh**
Domain for which certificate is asked for can be a CNAME, so we should check it.
If domain has a CNAME, create the challange TXT record in the alias domain.

### CODE REVIEW

**Comment by ldez** [comment]
Similar to #506

**Comment by gurvindersingh** [comment]
Ah ok.. didn't saw that one before. Feel free to choose which one you prefer and close the other one.

**Comment by vejnar** [comment]
Would be very nice to get this merged. It seems tests have failed but it doesn't seems to me to be a problem with your code. Could you try to do it again please?

**Comment by vejnar** [comment]
I looked in more  details. One test in b/providers/dns/acmedns/acmedns_test.go is in fact failing. The FQDN is setup but there is a CNAME for that FQDN. So with this patch, test passes.

```
+++ b/providers/dns/acmedns/acmedns_test.go
@@ -18,7 +18,7 @@ var (
 
        // Fixed test data for unit tests.
        egDomain  = "threeletter.agency"
-       egFQDN    = "_acme-challenge." + egDomain + "."
+       egFQDN    = "30feb5f3-7cfa-43e2-95aa-d42ca56db9b0.pki.threeletter.agency."
        egKeyAuth = "⚷"
        egAccount = goacmedns.Account{
                FullDomain: "acme-dns." + egDomain,
```
Could you please add this patch do your pull request?

**Comment by vejnar** [comment]
This pull request is pending for quite a while. As automatic tests have passed and the request seems pretty simple, I would like to know how we can get this merged.

Is there any way to get some attention to review and eventually merge from appropriate people?

**Comment by ldez** [comment]
Sorry, we try to do our best with the time we have :clock1:

**Comment by Daegalus** [comment]
Any updates on this? We currently rely on Acme.sh to do stuff like this doing shellouts from our apps because its one of the few ACME implementations that support CNAMEing. 

We are currently writing a general tool for our internal users, and have put a pause on it in hopes we get proper support in this golang lib.

This is quite useful/important to a multi project GCP organization that has a lot of DNS Zones in control of the teams, with a central DNS zone delegating to those zones that the teams don't have control over. CNAME checking has been a major success in our stack and in supporting our infrastructure for internal teams.

**Comment by mhoran** [comment]
I've rebased this PR and opened #791.

**Pull request closed without merging**
