### PR TITLE
add Name.com provider

### PR DESCRIPTION
**Pull request by pmoroney**
This PR adds Name.com as a provider for the DNS challenge.

### CODE REVIEW

**Comment by mholt** [comment]
Oh -- actually, you should also add the docs for this provider to [cli.go](https://github.com/xenolf/lego/blob/cc326ce155a7916c7a784aafb3c845722a4da698/cli.go#L201).

**Comment by pmoroney** [comment]
I submitted this as a first step to getting it added to Caddy :)
I didn't know about cli.go and will add that shortly.

**Comment by pmoroney** [comment]
Is there anything else that this PR needs?

**Comment by mholt** [comment]
Nah, I think that's good. Can you add an adapter for Caddy? :smile: Thanks!

**Comment by pmoroney** [comment]
Sure thing :)

**Pull request merged**
