### PR TITLE
New ultradns provider

### PR DESCRIPTION
**Pull request by Nitecon**

### CODE REVIEW

**Comment by xenolf** [comment]
Hey there!

Thank you for implementing this provider. Before I merge this in I wanted to ask you whether you are able to support this provider further in case any bugs or other problems occur.
Could you please add your provider to the CLI [here](https://github.com/xenolf/lego/blob/master/cli_handlers.go#L116) as well? Otherwise people won't be able to use it from the CLI.
Thank you!

**Comment by Nitecon** [comment]
Sure will add it to the CLI and yes I will support it.

**Comment by Nitecon** [comment]
Updated PR should be coming shortly I'm on PTO but will try to get it in soon.

**Comment by ldez** [comment]
@Nitecon any news?

**Comment by Nitecon** [comment]
Hey folks I'm unfortunately no longer at Neustar and no longer work with the ultradns team, we'll have to remove this contrib at this point and perhaps some of my previous coworkers will pick this up in the future.

**Comment by ldez** [comment]
I close this PR because it can not be finalized or maintained by the contributor.

Thanks anyway for the contribution.

**Pull request closed without merging**
