### PR TITLE
Add DNS Provider for Oracle Cloud

### PR DESCRIPTION
**Pull request by Sugi275**
Hi,
lego is a great tool! I’m very impressed.
I send PR.
Add DNS Provider for the Oracle Cloud DNS.

### lego run log with oracle cloud

```
> ./dist/lego --email="foo@bar.com" --domains="sugi.tokyo" --dns="oraclecloud" --server "https://acme-staging-v02.api.letsencrypt.org/directory" run
2019/02/25 07:00:26 [INFO] [sugi.tokyo] acme: Obtaining bundled SAN certificate
2019/02/25 07:00:27 [INFO] [sugi.tokyo] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/TQ-bYmPDubp8Ri3z6mJbkvpr6cv1-tKybazO7S8ReZU
2019/02/25 07:00:27 [INFO] [sugi.tokyo] acme: Could not find solver for: tls-alpn-01
2019/02/25 07:00:27 [INFO] [sugi.tokyo] acme: Could not find solver for: http-01
2019/02/25 07:00:27 [INFO] [sugi.tokyo] acme: use dns-01 solver
2019/02/25 07:00:27 [INFO] [sugi.tokyo] acme: Preparing to solve DNS-01
2019/02/25 07:00:31 [INFO] [sugi.tokyo] acme: Trying to solve DNS-01
2019/02/25 07:00:31 [INFO] [sugi.tokyo] acme: Checking DNS record propagation using [127.0.0.53:53]
2019/02/25 07:00:31 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2019/02/25 07:00:36 [INFO] [sugi.tokyo] The server validated our request
2019/02/25 07:00:36 [INFO] [sugi.tokyo] acme: Cleaning DNS-01 challenge
2019/02/25 07:00:40 [INFO] [sugi.tokyo] acme: Validations succeeded; requesting certificates
2019/02/25 07:00:41 [INFO] [sugi.tokyo] Server responded with a certificate.
```

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:
- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests ("live" and units)
```shell
make test
```
- [ ] add [documentation](https://github.com/xenolf/lego/blob/master/CONTRIBUTING.md#dns-providers-api-references)
- [ ] add CLI DNS help: https://github.com/xenolf/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/cmd/cmd_dnshelp.go#L19
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf ./lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -s https://acme-staging-v02.api.letsencrypt.org/directory -d *.example.com -d example.com run
```
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```

**Comment by ldez** [comment]
Also could you put the code of `envConfigProvider` inside Lego instead of an external lib.
Thanks.

**Comment by ldez** [comment]
could you do:

```
rm -rf ./lego

./dist/lego -m your@email.com  --dns="oraclecloud" -s https://acme-staging-v02.api.letsencrypt.org/directory -d *.sugi.tokyo -d sugi.tokyo run
```

Note the wildcard domain is important.

**Comment by Sugi275** [comment]
Thanks, your review, and fix!

I do lego run, but error...
I am debugging. Please wait.

```
> ./dist/lego -m sugi.mount@gmail.com  --dns="oraclecloud" -s https://acme-staging-v02.api.letsencrypt.org/directory -d '*.sugi.tokyo' -d 'sugi.tokyo' run
2019/02/26 03:56:31 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
                Your account credentials have been saved in your Let's Encrypt
                backups of this folder is ideal.2019/02/26 03:56:33 [INFO] [*.sugi.tokyo, sugi.tokyo] acme: Obtaining bundled SAN certificate
2019/02/26 03:56:34 [INFO] [*.sugi.tokyo] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/eCl79IDh2UkmSW5erDXwVgDjmtpO4QeVfgi4AyrnLRc
2019/02/26 03:56:34 [INFO] [sugi.tokyo] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/pz7xMlNFHvasLEqGYQotBZEV29NmIVKoYyN7gjhYeFg
2019/02/26 03:56:34 [INFO] [*.sugi.tokyo] acme: use dns-01 solver
2019/02/26 03:56:34 [INFO] [sugi.tokyo] acme: Could not find solver for: tls-alpn-01
2019/02/26 03:56:34 [INFO] [sugi.tokyo] acme: Could not find solver for: http-01
2019/02/26 03:56:34 [INFO] [sugi.tokyo] acme: use dns-01 solver
2019/02/26 03:56:34 [INFO] [*.sugi.tokyo] acme: Preparing to solve DNS-01
2019/02/26 03:56:38 [INFO] [sugi.tokyo] acme: Preparing to solve DNS-01
2019/02/26 03:56:43 [INFO] [*.sugi.tokyo] acme: Trying to solve DNS-01
2019/02/26 03:56:43 [INFO] [*.sugi.tokyo] acme: Checking DNS record propagation using [127.0.0.53:53]
2019/02/26 03:56:43 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2019/02/26 03:56:43 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:56:45 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:56:47 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:56:49 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:56:52 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:56:54 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:56:56 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:56:58 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:00 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:02 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:04 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:06 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:08 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:10 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:12 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:14 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:16 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:18 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:20 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:22 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:24 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:26 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:28 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:30 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:33 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:35 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:37 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:39 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:41 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:43 [INFO] [*.sugi.tokyo] acme: Waiting for DNS record propagation.
2019/02/26 03:57:45 [INFO] [sugi.tokyo] acme: Trying to solve DNS-01
2019/02/26 03:57:45 [INFO] [sugi.tokyo] acme: Checking DNS record propagation using [127.0.0.53:53]
2019/02/26 03:57:45 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2019/02/26 03:57:53 [INFO] [sugi.tokyo] The server validated our request
2019/02/26 03:57:53 [INFO] [*.sugi.tokyo] acme: Cleaning DNS-01 challenge
2019/02/26 03:57:56 [INFO] [sugi.tokyo] acme: Cleaning DNS-01 challenge
2019/02/26 03:57:58 Could not obtain certificates:
        acme: Error -> One or more domains had a problem:
[*.sugi.tokyo] time limit exceeded: last error: NS ns2.p68.dns.oraclecloud.net. did not return the expected TXT record [fqdn: _acme-challenge.sugi.tokyo., value: x2UnqsGX8XD0oUsWhyKsn__EaBWjKq1cgsJX_tk0Vk4]: wy9QS4s-OUWoQPdaShlpxn-kAP9esd-546neDyunuAA
```

**Comment by Sugi275** [comment]
Fix bug!

lego run succeccful

```
> ./dist/lego -m sugi.mount@gmail.com  --dns="oraclecloud" -s https://acme-staging-v02.api.letsencrypt.org/directory -d '*.sugi.tokyo' -d 'sugi.tokyo' run
2019/02/26 06:44:33 [INFO] [*.sugi.tokyo, sugi.tokyo] acme: Obtaining bundled SAN certificate
2019/02/26 06:44:34 [INFO] [*.sugi.tokyo] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/ogcPcUQosF8gjOpqTBH73bHbU-FdMo4bW3Qj4x9qI8E
2019/02/26 06:44:34 [INFO] [sugi.tokyo] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/WZbWJReSCvpMCHDFilejSqJtdVS0U8T57fTJkVJtth8
2019/02/26 06:44:34 [INFO] [*.sugi.tokyo] acme: use dns-01 solver
2019/02/26 06:44:34 [INFO] [sugi.tokyo] acme: Could not find solver for: tls-alpn-01
2019/02/26 06:44:34 [INFO] [sugi.tokyo] acme: Could not find solver for: http-01
2019/02/26 06:44:34 [INFO] [sugi.tokyo] acme: use dns-01 solver
2019/02/26 06:44:34 [INFO] [*.sugi.tokyo] acme: Preparing to solve DNS-01
2019/02/26 06:44:39 [INFO] [sugi.tokyo] acme: Preparing to solve DNS-01
2019/02/26 06:44:44 [INFO] [*.sugi.tokyo] acme: Trying to solve DNS-01
2019/02/26 06:44:44 [INFO] [*.sugi.tokyo] acme: Checking DNS record propagation using [127.0.0.53:53]
2019/02/26 06:44:44 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2019/02/26 06:44:50 [INFO] [*.sugi.tokyo] The server validated our request
2019/02/26 06:44:50 [INFO] [sugi.tokyo] acme: Trying to solve DNS-01
2019/02/26 06:44:50 [INFO] [sugi.tokyo] acme: Checking DNS record propagation using [127.0.0.53:53]
2019/02/26 06:44:50 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2019/02/26 06:44:50 [INFO] [sugi.tokyo] The server validated our request
2019/02/26 06:44:50 [INFO] [*.sugi.tokyo] acme: Cleaning DNS-01 challenge
2019/02/26 06:44:54 [INFO] [sugi.tokyo] acme: Cleaning DNS-01 challenge
2019/02/26 06:44:57 [INFO] [*.sugi.tokyo, sugi.tokyo] acme: Validations succeeded; requesting certificates
2019/02/26 06:45:00 [INFO] [*.sugi.tokyo] Server responded with a certificate.
```

**Comment by Sugi275** [comment]
Could I put document for set shell-env in oraclecloud directory?

Exapmle

```
export OCI_PRIVKEY_BASE64=`base64 ~/.oci/oci_api_key.pem`
export OCI_PRIVKEY_PASS="secret"
export OCI_TENANCY_OCID="ocid1.tenancy.oc1..secret"
export OCI_USER_OCID="ocid1.user.oc1..secret"
export OCI_PUBKEY_FINGERPRINT="00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00"
export OCI_REGION="us-phoenix-1"
export OCI_COMPARTMENT_OCID="ocid1.tenancy.oc1..secret"
```

**Comment by Sugi275** [comment]
>  be able to maintain this provider

OK.
Is there anything what should I do now?

**Comment by Sugi275** [comment]
Thanks, review and marge! :smile:

**Pull request merged**
