### PR TITLE
Fix out of range

### PR DESCRIPTION
**Pull request by rekby**
Some time (near once per 50-100 certificates) lego fails with stack:
panic: runtime error: index out of range

goroutine 1906 [running]:
panic(0x8781a0, 0xc8200100b0)
        C:/Go/src/runtime/panic.go:464 +0x3e6
github.com/xenolf/lego/acme.(*jws).Nonce(0xc820374300, 0x0, 0x0, 0x0, 0x0)
        c:/Users/Tim/Documents/go/src/github.com/xenolf/lego/acme/jws.go:105 +0x176
gopkg.in/square/go-jose%2ev1.(*genericSigner).Sign(0xc8203923c0, 0xc8205a6240, 0x6b, 0x8b, 0x6d0778650c48, 0x0, 0x0)
        c:/Users/Tim/Documents/go/src/gopkg.in/square/go-jose.v1/signing.go:157 +0x376
github.com/xenolf/lego/acme.(*jws).signContent(0xc820374300, 0xc8205a6240, 0x6b, 0x8b, 0x481c4b, 0x0, 0x0)
        c:/Users/Tim/Documents/go/src/github.com/xenolf/lego/acme/jws.go:70 +0x1f5
github.com/xenolf/lego/acme.(*jws).post(0xc820374300, 0xc8200144c0, 0x33, 0xc8205a6240, 0x6b, 0x8b, 0x0, 0x0, 0x0)
        c:/Users/Tim/Documents/go/src/github.com/xenolf/lego/acme/jws.go:35 +0x69
github.com/xenolf/lego/acme.postJSON(0xc820374300, 0xc8200144c0, 0x33, 0x8bd040, 0xc8205a61b0, 0x79dc80, 0xc8205a6120, 0x0, 0x0, 0x0)
        c:/Users/Tim/Documents/go/src/github.com/xenolf/lego/acme/http.go:96 +0x1df
github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0xc820024510, 0xc82022c780, 0xc82022c720, 0xc8204342b9, 0xb)
        c:/Users/Tim/Documents/go/src/github.com/xenolf/lego/acme/client.go:408 +0x1a7
created by github.com/xenolf/lego/acme.(*Client).getChallenges
        c:/Users/Tim/Documents/go/src/github.com/xenolf/lego/acme/client.go:421 +0x17c

### CODE REVIEW

**Comment by xenolf** [comment]
Hey and thanks for figuring this out and fixing it! :)

I've noticed that this change broke the tests. Would you mind fixing them up?

**Comment by rekby** [comment]
Done

**Comment by xenolf** [comment]
Thanks for fixing the tests.
I'm afraid the retry you added has no effect tho. We only ever have one running request at any given time and if there is no nonce for this request, there will never be with the current code. It would be a better idea to call `getNonce()` if we are starved of nonces to get a fresh one.

**Comment by rekby** [comment]
I have checked the sources:
getNonce has unconditional call httpHead at first line.
httpHead create new request and get header every time.

re-call getNonce will try get http headers every time.

Or I don't understand what you want say to me.

**Comment by xenolf** [comment]
No you are right, `getNonce` will make a HEAD request to the ACME server. This is intentional as new nonces only come from the server. In order to get a new one we have to hit the server and extract the new nonce from the headers.

**Comment by rekby** [comment]
Ok. I revert patch to simple - without retry, but it is workaround only.

I research the code and I see - the error impossible in single thread code. It may be only race condition.
calls getNonce -> getNonceFromResponse always return error or j.nonces length more then zero by append nonce in getNonceFromResponse
	j.nonces = append(j.nonces, nonce)

May be many goroutines work with the nonces same time and it need guard by mutex or redesign working with nonces?

**Comment by rekby** [comment]
I use lego as library in own code. My code is single thread/goroutine, but it is long running loop: I retrieving many hundreds certificates in a loop without restart program.

**Comment by xenolf** [comment]
> My code is single thread/goroutine, but it is long running loop: I retrieving many hundreds certificates in a loop without restart program.

That shouldn't be a problem. The client instance itself isn't thread safe yet tho. See #173.

**Pull request merged**
