### PR TITLE
Add manual validation for http-01 challenge

### PR DESCRIPTION
**Pull request by xi2**
Since it didn't seem like a lot of code, I added support for manual validation for http-01. The requesting issue (#60) has two +1s.

I based the file `http_challenge_manual.go` on `dns_challenge_manual.go`.

### CODE REVIEW

**Comment by beevik** [comment]
Just out of curiosity, is there any reason why this provider isn't in `providers/http`?  (Same question for manual DNS)

**Comment by xi2** [comment]
@beevik, I put `http_challenge_manual.go` in acme, since I just took `dns_challenge_manual.go` and modified it. I believe manual DNS is in acme, not providers, for reasons discussed in #111. Referring to manual DNS there, @xenolf said

> The manual provider should remain in the package as I think every challenge should be solvable by just importing the package.

However, that is not true of manual HTTP, so I can see an argument for putting that in providers. However I can also see an argument for keeping it in acme for symmetry with DNS manual, and the fact acme has HTTPProviderServer too.

I have no strong feelings on where it should live, so will move it wherever necessary.

**Comment by xenolf** [comment]
It is not about manual providers being in the ACME package but the "default" ones. For HTTP-01 this is serving the challenge on port 80, for TLS-SNI-01 that's serving it on port 443 and for DNS-01 it's the manual one. All other providers should go into `providers/challenge/provider`.

**Comment by xenolf** [comment]
> (Same question for manual DNS)

@beevik I believe that just by importing the ACME package all challenges we support should be solvable.

**Comment by xi2** [comment]
Understood @xenolf. I'll move it to providers/http/manual.

**Comment by xi2** [comment]
It is now living happily in providers :)

**Comment by xenolf** [comment]
I'm thinking about a way of not having to add a new stand-alone CMD switch for every HTTP-01 provider :laughing:

We have `--http`, `--webroot` and with this we get `--manual`. IMO those should be brought together and all have "http" somewhere in their name to label them as belonging to the HTTP-01 challenge.

**Comment by xi2** [comment]
I agree. That though crossed my mind too.

**Comment by xi2** [comment]
Just a suggestion without giving it too much thought. Free up the `--http` and `--tls` flags to make them symmetrical with `--dns`. So you can then specify `--http manual` or `--http webroot`. Then specify the ports some other way, such as `--http-port` and `--tls-port`. I quite like the idea that `--dns`, `--http`, and `--dns` all do that same thing logically i.e. specify a provider.

**Comment by xenolf** [comment]
Yes, I guess having a uniform interface to specify providers with `--http` `--tls` and `--dns` seems logical. For the address:port we could use `--http-address` and `--tls-address`. (Is there a name defined for the ip:port tuple?)

**Comment by xi2** [comment]
Yes, sorry. I meant `--http-address`, not `--http-port`. Need more coffee. I'm not aware of a special name for ip:port. I personally think address is fine.

**Comment by xenolf** [comment]
>  Need more coffee.

Yes... I do as well. Today is a productive day ;)

**Comment by xi2** [comment]
:) :) If you want, I can whip up a separate PR for this. Otherwise, I'm fine to wait, since I don't use this. It just seemed that #60 seemed an easy issue to knock off.

**Comment by xi2** [comment]
First attempt at flag renaming in #160.

**Comment by egeland** [comment]
Really hoping for `--manual` mode as my whole workflow relies on it (I push my static content to a cloud provider bucket-as-a-website).
I can do it with the `certbot`, but `lego` seems slicker.. :grinning:

**Pull request closed without merging**
