### PR TITLE
add memcached provider

### PR DESCRIPTION
**Pull request by clinta**
This adds a memcached provider for use with nginx's memcached module.

### CODE REVIEW

**Comment by xenolf** [comment]
Hello there!

Thank you for providing this!
Would it be possible to add unit tests to the provider?

**Comment by clinta** [comment]
Would it be okay to edit the travis config so that memcached is running in travis where the tests will run? Or is there an expectation that the tests can be run without any external dependencies? If so I'll have to find some good way to mock a memcached instance.

**Comment by xenolf** [comment]
I don't have any objections against adding memcached to travis if that's possible.
The only requirement I have is that `go test ./...` does also function without the dependecy. Basically as most of the DNS providers are doing based on if an ENV variable is set or not. Doing it via an ENV variable is not required though, that's up to you.

**Comment by clinta** [comment]
Rebased and added tests.

**Pull request merged**
