### PR TITLE
netcup: make unmarshalling of api-responses more leniant.

### PR DESCRIPTION
**Pull request by nnexai**
At the moment netcup-provider cannot be used, since unmarshal of responsedata fails.

When using through traefik on a kubernetes cluster i get:
```
time="XXXX" level=error msg="Unable to obtain ACME certificate for domains \"*.XXX,XXX\" : unable to generate a certificate for the domains [*.XXX XXX]: acme: Error -> One or more domains had a problem:\n[XXX] error presenting token: netcup: error decoding response of DNS-API, json: cannot unmarshal string into Go struct field ResponseMsg.responsedata of type netcup.ResponseData\n"
```

Currently responsedata on login only features apisessionid.
I assume the same holds true for GetDNSRecords not containing apisessionid

Example of a login response
```json
{
    "serverrequestid": "XXXX",
    "clientrequestid": "",
    "action": "login",
    "status": "success",
    "statuscode": 2000,
    "shortmessage": "Login successful",
    "longmessage": "Session has been created successful.",
    "responsedata": {
        "apisessionid": "XXXXX"
    }
}
```

Since dnsrecords is missing from responsedata in login-response unmarshal fails.

I moved error responses to the r.Status != success path to work around this problem.

Since I don't program in go and have little understanding of go's json mechanisms  I just wanted to point out the problem and add a small workaround -- feel free to change and adapt to your liking.

### CODE REVIEW

**Comment by ldez** [comment]
```
json: cannot unmarshal string into Go struct field ResponseMsg.responsedata of type netcup.ResponseData
```

This error mean that the type of `ResponseMsg.responsedata` is a string and not an object.

From the [documentation](https://ccp.netcup.net/run/webservice/servers/endpoint.php#Responsemessage) the type of `responsedata` seems to be a string.


If I understand correctly the specification, for me, the answer should be:

```json
{
    "serverrequestid": "XXXX",
    "clientrequestid": "",
    "action": "login",
    "status": "success",
    "statuscode": 2000,
    "shortmessage": "Login successful",
    "longmessage": "Session has been created successful.",
    "responsedata": "{\"apisessionid\": \"XXXXX\"}"
}
```

@nnexai Can you confirm that?

**Comment by ldez** [comment]
```
json: cannot unmarshal string into Go struct field ResponseMsg.responsedata of type netcup.ResponseData
```

This error mean that the type of `ResponseMsg.responsedata` is a string and not an object.

From the [documentation](https://ccp.netcup.net/run/webservice/servers/endpoint.php#Responsemessage) the type of `responsedata` seems to be a string.


If I understand correctly the specification, for me, the answer should be:

```json
{
    "serverrequestid": "XXXX",
    "clientrequestid": "",
    "action": "login",
    "status": "success",
    "statuscode": 2000,
    "shortmessage": "Login successful",
    "longmessage": "Session has been created successful.",
    "responsedata": "{\"apisessionid\": \"XXXXX\"}"
}
```

@nnexai Can you confirm that?

**Comment by nnexai** [comment]
When I tested it yesterday the response was as written in the PR (responsedata was an JSON object, not a string)

The docs also state (for login)

In responsedata field: string $apisessionid Server generated ID to be used with further requests when login was successful.

So I think this part is just messed up in the docs. I can do some simple curl testing for the other used functions as well later today, if this helps

**Comment by nnexai** [comment]
As tested yesterday, responsedata is usually a json object (only for logout it is an empty string). Just went through the calls manually:

login
```javascript
{
    "serverrequestid": "XXX",
    "clientrequestid": "",
    "action": "login",
    "status": "success",
    "statuscode": 2000,
    "shortmessage": "Login successful",
    "longmessage": "Session has been created successful.",
    "responsedata": {
        "apisessionid": "XYZ"
    }
}
```
logout
```javascript
{
    "serverrequestid": "XXX",
    "clientrequestid": "",
    "action": "logout",
    "status": "success",
    "statuscode": 2000,
    "shortmessage": "Logout successful",
    "longmessage": "Session has been terminated successful.",
    "responsedata": ""
}
```

infoDnsRecords
```javascript
{
    "serverrequestid": "XXX",
    "clientrequestid": "",
    "action": "infoDnsRecords",
    "status": "success",
    "statuscode": 2000,
    "shortmessage": "DNS records found",
    "longmessage": "DNS Records for this zone were found.",
    "responsedata": {
        "dnsrecords": [
            {
                "id": "1234",
                "hostname": "*",
                "type": "A",
                "priority": "0",
                "destination": "XXX.XXX.XXX.XXX",
                "deleterecord": false,
                "state": "yes"
            },
            ...
        ]
    }
}
```

updateDnsRecords
```javascript
{
    "serverrequestid": "XXX",
    "clientrequestid": "",
    "action": "updateDnsRecords",
    "status": "success",
    "statuscode": 2000,
    "shortmessage": "DNS records successful updated",
    "longmessage": "The given DNS records for this zone were updated.",
    "responsedata": {
        "dnsrecords": [
            {
                "id": "1234",
                "hostname": "*",
                "type": "A",
                "priority": "0",
                "destination": "XXX.XXX.XXX.XXX",
                "deleterecord": false,
                "state": "unknown"
            },
            ...
        ]
    }
}
```

**Pull request merged**
