### PR TITLE
Add support for webroot over ssh for http-01 challenge

### PR DESCRIPTION
**Pull request by yaslama**
This PR replace #16 (see also #27)

### CODE REVIEW

**Comment by mholt** [comment]
As far as I understand it, webroot basically places a file on the file system for the web server to serve up during the challenge, then the file can (should?) be deleted. I may be misunderstanding how it works, but I imagine we should make sure the token file gets cleaned up afterward, right?

Also, I'm not sure that building it directly into the client workflow is quite the right thing to do here. It seems like webroot is just one specific way of doing http-01 (not other challenges); instead of having a "web app" serve the response for the ACME server, you mimic that behavior for a static file server by plopping down a file at the right path.

Perhaps the actual _way_ the challenge is solved should be swappable... or something.

I think the "webroot" way of solving this challenge is good, but maybe there's a better way to design it for this library.

**Comment by zakjan** [comment]
I'd rather first implement "local webroot" instead of even more specific "webroot over ssh"

**Comment by yaslama** [comment]
Ok. I'll try to implement a way to "swap" the way to solve the challenge first.

**Comment by yaslama** [comment]
See #32 where I "extracted" the webserver method from http_challenge. If it's ok, I'll add the webroot methods for local filesystem and remote filesystem.

**Comment by xenolf** [comment]
This should probably get moved to an implementation using providers if you are up for it :)

**Pull request closed without merging**
