### PR TITLE
Expose challenge-related methods and types.

### LINKED ISSUE #378: Expose private client methods
I'd like to get a set of challenges, persist them someplace, and then later (i.e., in a separate request) solve the challenges and request a certificate. Because the relevant methods and types are all private, this isn't possible without copying and pasting a bunch of code from client.go. Would you be open to making `Client.getChallenges`, `Client.solveChallenges`, and `Client.requestCertificate` public methods, and `authorizationResource` a public type? I'd be happy to submit a patch if so.

cc @cnelson

### PR DESCRIPTION
**Pull request by jmcarp**
Resolves #378.

### CODE REVIEW

**Comment by jmcarp** [comment]
WDYT @xenolf ? I'll resolve merge conflicts if you're open to making these methods public.

**Comment by jmcarp** [comment]
Ping @xenolf

**Comment by xenolf** [comment]
Hello!

Sorry for leaving you hanging that long. I'm not opposed to this, but this is a breaking change and the newly exposed methods would need documentation.

**Comment by ldez** [comment]
I closed because it's outdated since v2.

**Pull request closed without merging**
